# Generated by Django 5.2 on 2025-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('mission_completed', 'Mission Completed'), ('badge_earned', 'Badge Earned'), ('leveled_up', 'Leveled Up'), ('info', 'Admin Info')], max_length=50),
        ),
    ]
