# Generated by Django 5.2 on 2025-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='condition_expression',
            field=models.TextField(default=True, help_text="Expresión Python evaluable: ejemplo 'level >= 5 or missions_completed >= 10'"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition_code',
            field=models.CharField(help_text='Codigo de condicion para desbloqueo (para logica interna)', max_length=100, unique=True),
        ),
    ]
