# Generated by Django 5.2 on 2025-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_usermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('github_commit', 'GitHub Commit'), ('github_pr', 'GitHub Pull Request')], default='manual', max_length=30),
        ),
    ]
