# Generated by Django 5.2 on 2025-06-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_mission_metadata_mission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('github_event', 'GitHub Event')], default='manual', max_length=30),
        ),
    ]
