# Generated by Django 5.2 on 2025-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_mission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='time_limit_days',
            field=models.PositiveIntegerField(blank=True, help_text='Días desde la creación para completar la misión. Dejar vacío si no hay límite.', null=True),
        ),
    ]
